# another test
name: Test workflow

on: [push]

jobs:
  show_version:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Check version
        uses: avides/actions-project-version-check@v1.3.0
      - with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file-to-check: pom.xml