# another test
name: Test workflow

on: [push]

jobs:
  check_version:

    runs-on: ubuntu-18.04
    steps:
      - name: Extract Maven version
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: project

      - name: Show version
        run: echo ${{ steps.project.outputs.version }}