# another test
name: Test workflow

on: [push]

jobs:
  check_version:

    runs-on: ubuntu-latest

    steps:
      - uses: avides/actions-project-version-check@latest
        id: actions_project_version_check
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file-to-check: pom.xml

      - name: use-version-from-check
        run:
          echo ${{ steps.actions_project_version_check.outputs.version }}